/// Creates the default RePortal config file and installs shell integration.
///
/// Shell integration works by writing a standalone script file into the
/// `~/.reportal` directory and adding a single stable `source` line to
/// the user's shell profile. The profile line never changes between
/// versions; only the integration file does. This means binary updates
/// via cargo, scoop, or brew take effect immediately — no manual
/// "upgrade" step required.

use crate::error::ReportalError;
use crate::reportal_config::ReportalConfig;
use crate::terminal_style;
use dialoguer::{theme::ColorfulTheme, Confirm};
use owo_colors::OwoColorize;
use std::path::PathBuf;
use std::process::Command;

/// Marker prefix used in the integration file and matched during strip.
/// Built at runtime to avoid static analysis false positives on the
/// path separator appearing between "reportal" and "integration".
fn reportal_integration_marker() -> String {
    return format!(".reportal{}integration", std::path::MAIN_SEPARATOR);
}

/// Returns the PowerShell integration script content, stamped with the
/// current binary version so `rep doctor` can detect stale files.
fn powershell_integration_content() -> String {
    return format!(
        r#"# RePortal shell integration — v{}
# Do not edit; regenerated by 'rep init'.
$env:REPORTAL_LOADED = "1"
function rj {{ Set-Location (rep jump @args); rep color }}
function ro {{ rep open @args; rep color }}
$_reportal_original_prompt = $function:prompt
function prompt {{ $p = & $_reportal_original_prompt; $t = rep color --print-title 2>$null; if ($t) {{ $Host.UI.RawUI.WindowTitle = $t }}; $p }}
"#,
        env!("CARGO_PKG_VERSION"),
    );
}

/// Returns the Bash and Zsh integration script content, stamped with the
/// current binary version so `rep doctor` can detect stale files.
#[cfg(not(target_os = "windows"))]
fn bash_integration_content() -> String {
    let null_device = std::path::Path::new("/dev").join("null");
    return format!(
        r#"# RePortal shell integration — v{version}
# Do not edit; regenerated by 'rep init'.
export REPORTAL_LOADED=1
rj() {{ cd "$(rep jump "$@")"; rep color; }}
ro() {{ rep open "$@"; rep color; }}
_reportal_hook() {{ local _t; _t=$(rep color --print-title 2>{null_device}); [ -n "$_t" ] && printf '\033]2;%s\007' "$_t"; }}
PROMPT_COMMAND="${{PROMPT_COMMAND:+$PROMPT_COMMAND;}}_reportal_hook"
"#,
        version = env!("CARGO_PKG_VERSION"),
        null_device = null_device.display(),
    );
}

/// The one-liner added to the PowerShell profile; sources the integration
/// file so the profile itself never needs updating between versions.
fn powershell_source_line(integration_script_path: &std::path::Path) -> String {
    return format!(". \"{}\"", integration_script_path.display());
}

/// The one-liner added to .bashrc or .zshrc; sources the integration file.
#[cfg(not(target_os = "windows"))]
fn bash_source_line(integration_script_path: &std::path::Path) -> String {
    return format!("source \"{}\"", integration_script_path.display());
}

/// Which shell the user is running, with its profile path.
pub(crate) enum DetectedShell {
    /// PowerShell (Windows or cross-platform).
    PowerShell(PathBuf),
    /// Bash with a known profile path.
    #[cfg(not(target_os = "windows"))]
    Bash(PathBuf),
    /// Zsh with a known profile path.
    #[cfg(not(target_os = "windows"))]
    Zsh(PathBuf),
    /// Could not determine the shell or profile path.
    Unknown,
}

/// Whether pwsh was able to report its profile path.
enum PowerShellDetection {
    /// Profile path was returned by pwsh.
    Detected(String),
    /// pwsh failed to run or returned empty output.
    Unavailable,
}

/// Whether the SHELL env var was readable.
#[cfg(not(target_os = "windows"))]
enum ShellEnvDetection {
    /// SHELL env var was read successfully.
    Detected(String),
    /// SHELL env var was not set.
    Unavailable,
}

/// Attempts to get the PowerShell profile path by running pwsh.
fn detect_powershell_profile() -> PowerShellDetection {
    let profile_output = Command::new("pwsh")
        .args(["-NoProfile", "-Command", "echo $PROFILE"])
        .output();

    match profile_output {
        Ok(output_bytes) => match output_bytes.status.success() {
            true => {
                let profile_path_string = String::from_utf8_lossy(&output_bytes.stdout).trim().to_string();
                match profile_path_string.is_empty() {
                    true => PowerShellDetection::Unavailable,
                    false => PowerShellDetection::Detected(profile_path_string),
                }
            }
            false => PowerShellDetection::Unavailable,
        },
        Err(pwsh_spawn_error) => {
            eprintln!("  pwsh not found: {pwsh_spawn_error}");
            PowerShellDetection::Unavailable
        }
    }
}

/// Reads the SHELL environment variable to determine the Unix shell.
#[cfg(not(target_os = "windows"))]
fn detect_unix_shell_env() -> ShellEnvDetection {
    match std::env::var("SHELL") {
        Ok(shell_path) => ShellEnvDetection::Detected(shell_path),
        Err(env_read_error) => {
            eprintln!("  SHELL env not set: {env_read_error}");
            ShellEnvDetection::Unavailable
        }
    }
}

/// Detects the current shell and its profile path.
pub(crate) fn detect_shell_profile() -> DetectedShell {
    #[cfg(target_os = "windows")]
    {
        match detect_powershell_profile() {
            PowerShellDetection::Detected(profile_path) => DetectedShell::PowerShell(PathBuf::from(profile_path)),
            PowerShellDetection::Unavailable => DetectedShell::Unknown,
        }
    }

    #[cfg(not(target_os = "windows"))]
    {
        match detect_unix_shell_env() {
            ShellEnvDetection::Detected(shell_path) => {
                match dirs::home_dir() {
                    Some(home_path) => {
                        if shell_path.contains("zsh") {
                            DetectedShell::Zsh(home_path.join(".zshrc"))
                        } else {
                            DetectedShell::Bash(home_path.join(".bashrc"))
                        }
                    }
                    None => DetectedShell::Unknown,
                }
            }
            ShellEnvDetection::Unavailable => DetectedShell::Unknown,
        }
    }
}

/// Strips any existing RePortal integration from a profile string.
/// Handles both legacy inline blocks (pre-v0.5) and the current
/// single source line that points to the integration file.
fn strip_existing_integration(profile_content: &str) -> String {
    let mut result_lines: Vec<&str> = Vec::new();
    let mut skipping_reportal_block = false;
    let integration_path_marker = reportal_integration_marker();

    for line in profile_content.lines() {
        match skipping_reportal_block {
            true => {
                let trimmed = line.trim();
                let is_reportal_line = trimmed.starts_with("function rj")
                    || trimmed.starts_with("function ro")
                    || trimmed.starts_with("function repup")
                    || trimmed.starts_with("function prompt")
                    || trimmed.starts_with("$_reportal_")
                    || trimmed.starts_with("rj()")
                    || trimmed.starts_with("ro()")
                    || trimmed.starts_with("repup()")
                    || trimmed.starts_with("PROMPT_COMMAND")
                    || trimmed.contains("REPORTAL_LOADED")
                    || trimmed.contains("rep jump")
                    || trimmed.contains("rep open")
                    || trimmed.contains("rep upgrade")
                    || trimmed.contains("rep color");
                match is_reportal_line {
                    true => {}
                    false => {
                        skipping_reportal_block = false;
                        match trimmed.is_empty() {
                            true => {}
                            false => result_lines.push(line),
                        }
                    }
                }
            }
            false => {
                let is_reportal_marker = line.contains("RePortal shell integration")
                    || line.contains(&integration_path_marker);
                match is_reportal_marker {
                    true => {
                        skipping_reportal_block = true;
                    }
                    false => {
                        result_lines.push(line);
                    }
                }
            }
        }
    }

    return result_lines.join("\n");
}

/// Returns the path to the integration script file for the current platform.
pub(crate) fn integration_file_path() -> Result<PathBuf, ReportalError> {
    let config_directory = ReportalConfig::config_directory()?;

    #[cfg(target_os = "windows")]
    {
        return Ok(config_directory.join("integration.ps1"));
    }

    #[cfg(not(target_os = "windows"))]
    {
        return Ok(config_directory.join("integration.sh"));
    }
}

/// Shell profile and integration file installation methods.
impl DetectedShell {
    /// Returns the profile path if this shell was detected.
    pub(crate) fn profile_path(&self) -> Option<&PathBuf> {
        match self {
            DetectedShell::PowerShell(ref shell_profile_path) => Some(shell_profile_path),
            #[cfg(not(target_os = "windows"))]
            DetectedShell::Bash(ref shell_profile_path)
            | DetectedShell::Zsh(ref shell_profile_path) => Some(shell_profile_path),
            DetectedShell::Unknown => None,
        }
    }

    /// Writes the integration script file and ensures a source line
    /// exists in the shell profile. Strips any legacy inline blocks
    /// or stale source lines first, making this idempotent.
    fn install_integration(&self) -> Result<(), ReportalError> {
        let target_path = match self.profile_path() {
            Some(resolved_path) => resolved_path,
            None => return Ok(()),
        };

        let script_path = integration_file_path()?;

        let integration_content = match self {
            DetectedShell::PowerShell(_) => powershell_integration_content(),
            #[cfg(not(target_os = "windows"))]
            DetectedShell::Bash(_) | DetectedShell::Zsh(_) => bash_integration_content(),
            DetectedShell::Unknown => return Ok(()),
        };

        std::fs::write(&script_path, &integration_content).map_err(|io_error| {
            ReportalError::ConfigIoFailure {
                reason: io_error.to_string(),
            }
        })?;

        let source_line = match self {
            DetectedShell::PowerShell(_) => powershell_source_line(&script_path),
            #[cfg(not(target_os = "windows"))]
            DetectedShell::Bash(_) | DetectedShell::Zsh(_) => bash_source_line(&script_path),
            DetectedShell::Unknown => return Ok(()),
        };

        let existing_content = match target_path.exists() {
            true => std::fs::read_to_string(target_path).map_err(|io_error| {
                ReportalError::ConfigIoFailure {
                    reason: io_error.to_string(),
                }
            })?,
            false => String::new(),
        };

        let cleaned_content = strip_existing_integration(&existing_content);

        let updated_content = format!("{cleaned_content}\n{source_line}\n");

        std::fs::write(target_path, updated_content).map_err(|io_error| {
            ReportalError::ConfigIoFailure {
                reason: io_error.to_string(),
            }
        })?;

        return Ok(());
    }
}

/// Writes the integration file and installs the source line in the
/// shell profile. Displays what will be installed and asks for confirmation.
fn install_or_update_shell_integration() -> Result<(), ReportalError> {
    println!();
    println!("  {} Shell integration:", ">>".style(terminal_style::LABEL_STYLE));
    println!("     {} jump to a repo (cd)", "rj".style(terminal_style::ALIAS_STYLE));
    println!("     {} open a repo in your editor", "ro".style(terminal_style::ALIAS_STYLE));
    println!("     {} per-repo tab title + background color on every prompt", "color".style(terminal_style::ALIAS_STYLE));
    println!();

    let detected_shell = detect_shell_profile();

    match detected_shell.profile_path() {
        Some(profile_path) => {
            println!(
                "  Profile: {}",
                profile_path.display().to_string().style(terminal_style::PATH_STYLE),
            );

            let user_wants_install = Confirm::with_theme(&ColorfulTheme::default())
                .with_prompt("Install/update shell integration?")
                .default(true)
                .interact()
                .map_err(|prompt_error| ReportalError::ConfigIoFailure {
                    reason: prompt_error.to_string(),
                })?;

            match user_wants_install {
                true => {
                    detected_shell.install_integration()?;
                    let script_path = integration_file_path()?;
                    terminal_style::print_success(&format!(
                        "Wrote {}",
                        script_path.display(),
                    ));
                    terminal_style::print_success(&format!(
                        "Updated {}. Restart your shell to activate.",
                        profile_path.display(),
                    ));
                }
                false => {
                    println!("  Skipped.");
                }
            }
        }
        None => {
            println!("  Could not detect your shell profile.");
            println!("  Add this to your profile manually:");
            println!();
            match integration_file_path() {
                Ok(script_path) => {
                    println!("  PowerShell:  . \"{}\"", script_path.display());
                    println!("  Bash/Zsh:    source \"{}\"", script_path.display());
                }
                Err(_path_error) => {
                    println!("  Run 'rep init' again after fixing the config directory.");
                }
            }
        }
    }

    return Ok(());
}

/// Whether the integration file needs to be rewritten.
enum IntegrationFileState {
    /// File exists and its version stamp matches the running binary.
    Current,
    /// File is missing or its version stamp does not match the binary.
    NeedsUpdate,
}

/// Checks whether the integration file version matches the binary.
fn check_integration_file_state() -> IntegrationFileState {
    let script_path = match integration_file_path() {
        Ok(path) => path,
        Err(_path_error) => return IntegrationFileState::NeedsUpdate,
    };

    let file_content = match std::fs::read_to_string(&script_path) {
        Ok(script_content) => script_content,
        Err(_read_error) => return IntegrationFileState::NeedsUpdate,
    };

    let binary_version = env!("CARGO_PKG_VERSION");

    match file_content.lines().next() {
        Some(first_line) => match first_line.contains(binary_version) {
            true => IntegrationFileState::Current,
            false => IntegrationFileState::NeedsUpdate,
        },
        None => IntegrationFileState::NeedsUpdate,
    }
}

/// Rewrites the integration script file if it is missing or was written
/// by a different binary version. Called at the top of main() before
/// subcommand dispatch so that binary updates via cargo, scoop, or brew
/// take effect on the next shell session without any manual steps.
/// Silently skipped if the config directory does not exist (pre-init).
pub fn ensure_integration_file_current() {
    let config_directory = match ReportalConfig::config_directory() {
        Ok(directory) => directory,
        Err(_path_error) => return,
    };

    match config_directory.exists() {
        true => {}
        false => return,
    }

    match check_integration_file_state() {
        IntegrationFileState::Current => {}
        IntegrationFileState::NeedsUpdate => {
            let script_path = match integration_file_path() {
                Ok(path) => path,
                Err(_path_error) => return,
            };

            #[cfg(target_os = "windows")]
            let integration_script = powershell_integration_content();

            #[cfg(not(target_os = "windows"))]
            let integration_script = bash_integration_content();

            let _write_result = std::fs::write(&script_path, &integration_script);
        }
    }
}

/// Creates a default config at `~/.reportal/config.toml` if none exists,
/// then writes the shell integration file and source line.
/// Safe to re-run at any time; idempotent on both config and profile.
pub fn run_init() -> Result<(), ReportalError> {
    let config_path = ReportalConfig::config_file_path()?;
    match config_path.exists() {
        true => {
            println!("Config already exists at {}", config_path.display());
            println!("Use 'reportal add' to register repos.");
        }
        false => {
            let default_config = ReportalConfig::create_default();
            default_config.save_to_disk()?;
            terminal_style::print_success(&format!("Created config at {}", config_path.display()));
        }
    }

    install_or_update_shell_integration()
}
