/// Subcommand implementations for the RePortal CLI.
mod color_command_mode;
mod detected_shell;
mod doctor;
mod git_commands;
mod initialization;
mod integration_freshness;
mod path_display;
mod prompts;
mod repo_add;
mod repo_ai;
mod repo_color;
mod repo_edit;
mod repo_jump;
mod repo_listing;
mod repo_open;
mod repo_remove;
mod repo_run;
mod repo_selection;
mod repo_status;
mod terminal_identity_emit;
mod repo_sync;
mod repo_web;

pub use color_command_mode::ColorCommandMode;
pub use doctor::run_doctor;
pub use integration_freshness::ensure_integration_file_current;
pub use initialization::run_init;
pub use repo_add::run_add;
pub use repo_ai::{run_ai, AiCommandParams};
pub use repo_edit::{run_edit, EditCommandParams};
pub use repo_color::{run_color, ColorCommandParams};
pub use repo_jump::{run_jump, JumpCommandParams};
pub use repo_listing::run_list;
pub use repo_open::{run_open, OpenCommandParams};
pub use repo_remove::run_remove;
pub use repo_run::{run_run, RunCommandParams};
pub use repo_status::run_status;
pub use repo_sync::run_sync;
pub use repo_web::{run_web, WebCommandParams};
