//! Shell integration script content, stamped with the running
//! binary's version.
//!
//! The content is rendered to stdout by `rep init <shell>` and
//! consumed by the user's rc file via `eval "$(rep init zsh)"`.
//! There is no on-disk integration file — the script is regenerated
//! every shell session so a binary upgrade takes effect the next
//! time the user opens a terminal, with zero manual steps.
//!
//! `REPORTAL_LOADED` is stamped with the shell's own PID (`$$` in
//! bash/zsh, `$PID` in `PowerShell`) rather than the literal `1`,
//! so child processes which inherit the env var without sourcing
//! the integration become detectable: `rep` compares the value
//! against its parent process id at startup and treats a mismatch
//! as "marker inherited, integration not actually loaded in this
//! shell" — see `shell_integration_autowire`.

/// @why Renders the bash/zsh integration block for callers piping
/// it through `eval "$(rep init bash|zsh)"`.
#[must_use]
pub fn bash_integration_content() -> String {
    let null_device = std::path::Path::new("/dev").join("null");
    format!(
        r#"# RePortal shell integration — v{version}
# Generated by 'rep init bash|zsh'.
export REPORTAL_LOADED=$$
rj() {{ cd "$(rep jump "$@")"; rep color; }}
ro() {{ rep open "$@"; rep color; }}
rjw() {{ cd "$(rep workspace jump "$@")"; rep color; }}
row() {{ rep workspace open "$@"; rep color; }}
rw() {{ rep web "$@"; }}
rr() {{ rep run "$@"; }}
_reportal_hook() {{ local _t; _t=$(rep color --mode prompt-hook 2>{null_device}); [ -n "$_t" ] && printf '\033]2;%s\007' "$_t"; }}
PROMPT_COMMAND="${{PROMPT_COMMAND:+$PROMPT_COMMAND;}}_reportal_hook"
"#,
        version = env!("CARGO_PKG_VERSION"),
        null_device = null_device.display(),
    )
}

/// @why Renders the `PowerShell` integration block for callers
/// piping it through `Invoke-Expression (& rep init powershell |
/// Out-String)`. Uses `global:` scope qualifiers so the script
/// works the same whether sourced into `$PROFILE`, dot-sourced
/// into a module, or fed through any other loader.
#[must_use]
pub fn powershell_integration_content() -> String {
    format!(
        r#"# RePortal shell integration — v{}
# Generated by 'rep init powershell'.
$env:REPORTAL_LOADED = "$PID"
function global:rj {{ Set-Location (rep jump @args); rep color }}
function global:ro {{ rep open @args; rep color }}
function global:rjw {{ Set-Location (rep workspace jump @args); rep color }}
function global:row {{ rep workspace open @args; rep color }}
function global:rw {{ rep web @args }}
function global:rr {{ rep run @args }}
$script:_reportal_original_prompt = $function:global:prompt
function global:prompt {{ $p = & $script:_reportal_original_prompt; $t = rep color --mode prompt-hook 2>$null; if ($t) {{ $Host.UI.RawUI.WindowTitle = $t }}; $p }}
"#,
        env!("CARGO_PKG_VERSION"),
    )
}
