//! Shell integration script content, stamped with the running
//! binary's version.
//!
//! The content is rendered to stdout by `rep init <shell>` and
//! consumed by the user's rc file through a guarded eval block.
//! There is no on-disk integration file — the script is regenerated
//! every shell session so a binary upgrade takes effect the next
//! time the user opens a terminal, with zero manual steps.
//!
//! `REPORTAL_LOADED` is stamped with the shell's own PID (`$$` in
//! bash/zsh, `$PID` in `PowerShell`) rather than the literal `1`,
//! so child processes which inherit the env var without sourcing
//! the integration become detectable: `rep` compares the value
//! against its parent process id at startup and treats a mismatch
//! as "marker inherited, integration not actually loaded in this
//! shell" — see `shell_integration_autowire`.

const POSIX_REINSTALL_COMMAND: &str = "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/CheckPickerUpper/reportal/releases/latest/download/reportal-installer.sh | sh";

const POWERSHELL_REINSTALL_COMMAND: &str = "powershell -ExecutionPolicy Bypass -c \"irm https://github.com/CheckPickerUpper/reportal/releases/latest/download/reportal-installer.ps1 | iex\"";

/// @why Renders the bash/zsh integration block so shell startup can
/// regenerate wrappers from the current binary while preserving a
/// clear recovery path when the executable is missing.
#[must_use]
pub fn bash_integration_content() -> String {
    let null_device = std::path::Path::new("/dev").join("null");
    format!(
        r#"# RePortal shell integration — v{version}
# Generated by 'rep init bash|zsh'.
export REPORTAL_LOADED=$$
_reportal_reinstall_command="{reinstall_command}"
_reportal_missing_rep() {{ printf '%s\n' "RePortal: rep is not on PATH. Reinstall with: $_reportal_reinstall_command" >&2; }}
_reportal_rep_command() {{
    local _rep_path
    if [ -n "${{BASH_VERSION:-}}" ]; then
        _rep_path=$(type -P rep 2>{null_device}); [ -n "$_rep_path" ] && {{ printf '%s\n' "$_rep_path"; return 0; }}
    fi
    if [ -n "${{ZSH_VERSION:-}}" ]; then
        _rep_path=$(whence -p rep 2>{null_device}); [ -n "$_rep_path" ] && {{ printf '%s\n' "$_rep_path"; return 0; }}
    fi
    _rep_path=$(command -v reportal 2>{null_device}); [ -n "$_rep_path" ] && {{ printf '%s\n' "$_rep_path"; return 0; }}
    return 1
}}
rep() {{ local _rep; if _rep=$(_reportal_rep_command); then "$_rep" "$@"; else _reportal_missing_rep; return 127; fi; }}
rj() {{ local _target; _target=$(rep jump "$@") || return; cd "$_target" || return; rep color; }}
ro() {{ rep open "$@" && rep color; }}
rjw() {{ local _target; _target=$(rep workspace jump "$@") || return; cd "$_target" || return; rep color; }}
row() {{ rep workspace open "$@" && rep color; }}
rw() {{ rep web "$@"; }}
rr() {{ rep run "$@"; }}
_reportal_hook() {{ local _t; _t=$(rep color --mode prompt-hook 2>{null_device}); [ -n "$_t" ] && printf '\033]2;%s\007' "$_t"; }}
PROMPT_COMMAND="${{PROMPT_COMMAND:+$PROMPT_COMMAND;}}_reportal_hook"
"#,
        version = env!("CARGO_PKG_VERSION"),
        reinstall_command = POSIX_REINSTALL_COMMAND,
        null_device = null_device.display(),
    )
}

/// @why Renders the `PowerShell` integration block so profile
/// startup can refresh global wrappers from the current binary
/// while preserving a clear recovery path when `rep.exe` is
/// missing from the user PATH.
#[must_use]
pub fn powershell_integration_content() -> String {
    format!(
        r#"# RePortal shell integration — v{version}
# Generated by 'rep init powershell'.
$env:REPORTAL_LOADED = "$PID"
function global:rep {{
    $repApplication = Get-Command rep -CommandType Application -ErrorAction SilentlyContinue
    if (-not $repApplication) {{
        $repApplication = Get-Command reportal -CommandType Application -ErrorAction SilentlyContinue
    }}
    if ($repApplication) {{
        & $repApplication.Source @args
        return
    }}
    Write-Error 'RePortal: rep.exe is not on PATH. Reinstall with: {reinstall_command}'
    $global:LASTEXITCODE = 127
}}
function global:rj {{ $target = rep jump @args; if ($target) {{ Set-Location $target; rep color }} }}
function global:ro {{ rep open @args; if ($?) {{ rep color }} }}
function global:rjw {{ $target = rep workspace jump @args; if ($target) {{ Set-Location $target; rep color }} }}
function global:row {{ rep workspace open @args; if ($?) {{ rep color }} }}
function global:rw {{ rep web @args }}
function global:rr {{ rep run @args }}
$script:_reportal_original_prompt = $function:global:prompt
function global:prompt {{ $p = & $script:_reportal_original_prompt; $t = rep color --mode prompt-hook 2>$null; if ($t) {{ $Host.UI.RawUI.WindowTitle = $t }}; $p }}
"#,
        version = env!("CARGO_PKG_VERSION"),
        reinstall_command = POWERSHELL_REINSTALL_COMMAND,
    )
}
